# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b2803cf5bdb3623900888f5928208de497bc845a6fcb0c40edb00c13bd5489a2c61424bc9d900145f4520f9a03b0e50dcc7d409de96af24b03a0716ac3581c

test:
  secret_key_base: a0b4b684a7ced97cc30ba5294d881881966423fdd776d43ff316ff4bf7cd79b4ac804bba47c5f6e8c2dc49d06c5e2964e994677c2747c27dc6a3640fef021aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
